### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by cpicanco** [eugeneloza/Click2Foss#1]
Hi!

How to build the game for android and linux?

For linux I received:

```text
Fatal: Cannot find Interfaces used by CastleWindow. Check if package LCL is in the dependencies of package castle_window.
```

I am guessing it should not depend on LCL, so what can I do??

**Comment by eugeneloza** [comment]
Hi, @cpicanco!
Unfortunately I didn't finish the game (shame on me!). I've spent only 1 hour programming :(... Actually it's left just very basic interface/classes routines. So, nothing even to click...

> Fatal: Cannot find Interfaces used by CastleWindow. Check if package LCL is in the dependencies of package castle_window.
Did you install Caslte Game Engine? I've never used it with pure FPC. In Lazuarus you should install there three packages in folder `packages/` of the Engine: `castle_base.lpk`, `castle_window.lpk` and `castle_components.lpk` (however, the latter may be omitted, as the game doesn't use LCL).
You may also look at more detailed tutorial here https://castle-engine.sourceforge.io/documentation.php or even in video: https://www.youtube.com/watch?v=rCPEOw8700c

Cross-compiling to Android is a bit tricky (however, it isn't tricky on Castle Game Engine side, everything is more than simple there - it's tricky to set up FPC cross-compiler properly). You can read a tutorial on how to set everything up here: https://github.com/castle-engine/castle-engine/wiki/Android

**Comment by cpicanco** [comment]
Including LCL and LazOpenGLContext in Project Inspector package dependencies and it will compile and run. Though in "black" mode.. 

![screenshot - 10082017 - 05 13 38 pm](https://user-images.githubusercontent.com/6511849/31320513-256c1996-ac4c-11e7-9521-a971d3c12918.png)

**Comment by eugeneloza** [comment]
> Though in "black" mode..

Yes, I'm afraid that's all that has been made so far :(

The idea was to make a simple clicker game with a story. But I was too lazy these weekends, and have spent almost all my time testing RogueBoxAdventures. Nearly zero useful progress...

**Comment by cpicanco** [comment]
Thank you! Just to have this as staring point for me is of great help! Good work @eugeneloza !

PS.: I also changed `Vector4(1,1,1,1)` to `White` to compile.

**Comment by cpicanco** [comment]
I will try to port the runtime of a teaching machine to this new environment! I was studying OpenAL this week and have made some progress (I needed GPL substitute for BASS).

**Comment by eugeneloza** [comment]
You might wish to look at this game https://github.com/eugeneloza/SnakeGame ------- it's a complete game which features most things of Castle Game Engine that'll get you started in no-time (displaying graphics, text, loading resources, playing music and sound). Unfortunately, I didn't finish it's Android port, however, if you need that, ping me, I'll finish the job.

**Comment by eugeneloza** [comment]
Or you may directly look at Castle Game Engine example on playing audio: https://github.com/castle-engine/castle-engine/blob/master/examples/audio/alplay.lpr

**Comment by cpicanco** [comment]
Thanks @eugeneloza !
